version: "3.8"

services:
  message-broker:
    image: "rabbitmq:3.6.14-management"
    ports:
      - 5672:5672
      - 15672:15672

  game-server:
      build: ./
      links:
        - message-broker
      volumes:
        - ./:/usr/src/app
      ports:
        - 8000:8000
      command: "uvicorn main:app --host=0.0.0.0 --reload"

  leaderboard:
      build: ./
      links:
         - message-broker
      volumes:
         - ./:/usr/src/app
      command: "python test-leaderboard.py"

  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: DaftAcademy
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
      - ./:/home/app/
    ports:
      - "5555:5432"
volumes:
  postgres: